const DOWNLOAD_PHOTOS = 'DOWNLOAD_PHOTOS';
const REFRESH_CURRENT_PAGE = 'REFRESH_CURRENT_PAGE';
const DOWNLOAD_NEXT_PAGE = 'DOWNLOAD_NEXT_PAGE';
const PHOTOS_RECEIVED = 'PHOTOS_RECEIVED';
const SHARE_PHOTO = 'SHARE_PHOTO';

export {
    DOWNLOAD_PHOTOS,
    REFRESH_CURRENT_PAGE,
    DOWNLOAD_NEXT_PAGE,
    PHOTOS_RECEIVED,
    SHARE_PHOTO
}